### ISSUE TITLE
Gmod 13 error

### ISSUE THREAD

**Issue by headhunter108** [mattkrins/dodgeball#16]
So first when i start the game with 2 players so i could spawn bots the game begins and then the game says 404 error, but i can close it so i can continue but then i notice that there are script errors, but then when i try to spawn ai it either crashes or it has an error and it says this 

[ERROR] gamemodes/dodgeball/gamemode/core/plugins/sv_ai.lua:153: attempt to call field 'CreateNextBot' (a nil value)
  1. unknown - gamemodes/dodgeball/gamemode/core/plugins/sv_ai.lua:153
   2. unknown - lua/includes/modules/concommand.lua:69

**Comment by mattkrins** [comment]
You are either running an out-dated version of Garry's Mod or running the gamemode in a bad instance (such as singleplayer).

The error is saying that the function [![](http://wiki.garrysmod.com/favicon.ico) player.CreateNextBot](http://wiki.garrysmod.com/page/player/CreateNextBot) does not exist, however as you can see it most certainly does and has for years.
