### ISSUE TITLE
crash to desktop

### ISSUE THREAD

**Issue by RyWillo** [mattkrins/dodgeball#8]
Hey, there is a crash to desktop on Skyscraper when the timer hits around 5-6 it crashes. No crash log found what so ever

when "New Round Starting" is said in chat, it crashes

**Comment by mattkrins** [comment]
Was this after or before the first round had started?
I've been getting a few crashes myself, i'm thinking it might be due to the nature of the maps as they were not build for gmod.

**Comment by RyWillo** [comment]
before the first round started

**Comment by mattkrins** [comment]
Looks like this is not limited to the skyscraper map, still investigating.

**Comment by mattkrins** [comment]
Narrowed this down to an issue with multiplayer games. Continuing investigation.

**Comment by mattkrins** [comment]
Issue fixed in next version, turned out to be the viewmodel for the dodgeball swep, it would crash gmod after loading into the source engine a second time.

**Comment by mattkrins** [comment]
Version 2.0 Released.
